language: python
python:
  - 2.7.8
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  - pypy3
cache: pip
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.1
# commands to install dependencies
install:
  - pip install --upgrade pip coverage codecov
  - python setup.py -q install
  - pip install -q Django==$DJANGO_VERSION
# commands to run tests
script:
  - python system_architect/manage.py makemigrations system_architect
  - python system_architect/manage.py migrate
  - coverage run --source='.' system_architect/manage.py test system_architect
  - coverage report -m
  - codecov --token=$CODECOV_TOKEN